### ISSUE TITLE
Cannot locate DDI on Linux

### ISSUE THREAD

**Issue by ruslankotl** [lmmentel/chemtools#2]
Use of Gamess wrapper impossible on Linux machines due to chemtools providing an invalid command to the shell resulting in a DDI error and failed computation. Could you rework get_command module to provide a proper command as in pygamess:
`exec_string = "{0} {1} {2} -ddi {3} {3} {4} -scr {5} > {6}".format(ddikick, gamess, self.jobname,
                    self.num_cores, hostname, self.tempdir, self.gamout)`
where ddikick is a path to DDI, gamess is a path to executable, self.jobname is an input file, num_cores is a number of cores, self.tempdir is a scratch folder, and self.gamout is an output file.

**Comment by lmmentel** [comment]
Hi @ruslankotl Thanks for taking the time to report this. Could you paste the actual error you're getting and a minimal example I could reproduce?

**Comment by ruslankotl** [comment]
Thank you for getting back @lmmentel 

So I was following your [https://chemtools.readthedocs.io/en/latest/notebooks/GamessUS_tutorial.html](tutorial for Gamess(US)) using a new version Jupyter Notebook with Ubuntu 20.04 LTS installed on WSL.

Setting up the calculator was reasonably easy:

`gamess = GamessUS(executable="/home/ruslan/gamess/gamess.01.x",
                version="01",
                runopts=["1"],
                scratch="/home/ruslan/scr")`

rungms and ddikick methods have pointed to the correct locations, however your original method with specifying exevar instead of execultable did not work (should I have set up .bashrc?)

I then followed the instructions further, however instead of the result I have got the following message:

 DDI Process 0: error code 911
 DDI: Invalid command-line arguments!
 Are you using the ddikick program??

Running the input file through the terminal directly worked normally.

**Comment by lmmentel** [comment]
I tried the tutorial you mention with the latest version of gamess and all works fine. It seems to me that you might have some configuration issues related to your gamess installation. To verify that you gamess installation runs OK try executing some examples directly from the terminal using `rungms` comman, if that works `chemtools` should work as well.

**Comment by ruslankotl** [comment]
> I tried the tutorial you mention with the latest version of gamess and all works fine. It seems to me that you might have some configuration issues related to your gamess installation. To verify that you gamess installation runs OK try executing some examples directly from the terminal using `rungms` comman, if that works `chemtools` should work as well.

That's the thing: executing the example with `chemtools` yields a DDI error, but executing the example with `!  ~/gamess/rungms h2_test1.inp 01 4 >& h2_test1.log` within the same Jupyter Notebook proceeds normally.

**Comment by lmmentel** [comment]
Could you try using the path to your `rungms` as executable? I guess it should look something like 

```
gamess = GamessUS(executable="/home/ruslan/gamess/rungms", version="01", runopts=["1"], scratch="/home/ruslan/scr")
```

and try again?

**Comment by ruslankotl** [comment]
Seemed to work, thank you very much!
