### ISSUE TITLE
Some questions about your chemtools programes

### ISSUE THREAD

**Issue by hyh2022** [lmmentel/chemtools#3]
Hi, Dr. Mentel. I have used 'pip' to install your chemtools and the program to read two-electrons integrals from Gamess-us. I have followed your tutorial, but there are some questions. Firstly, the modules 'gamessreader' and 'gamessus' are in the calculators floder, but there are 'from chemtools.gamessreader' and 'from chemtools.gamessus'. So, I have changed my python program based on your tutorial. When I run my python program, it will get '.F' files, however, it will be a new error which says name 'twoe' is not defined. The 'twoe' is in the module gamessreader.py.I have put my python program which I wrote following your tutorial, bash script and error.out in the appendix. Please find them attached. It will be appreciated to hear from you asap.
[run.sh.txt](https://github.com/lmmentel/chemtools/files/7927038/run.sh.txt)
[twoint.py.txt](https://github.com/lmmentel/chemtools/files/7927039/twoint.py.txt)

**Comment by hyh2022** [comment]
this is the error.out
[error.out.txt](https://github.com/lmmentel/chemtools/files/7964092/error.out.txt)

**Comment by lmmentel** [comment]
Thanks, could you point me to which tutorial you followed? If you paste a link to the docs it should be enough.

**Comment by hyh2022** [comment]
[GamessFortranReader_tutorial](https://github.com/lmmentel/chemtools/blob/master/examples/ipython_notebooks/GamessFortranReader_tutorial.ipynb)

**Comment by lmmentel** [comment]
The notebook you mention is not part of the official docs and is outdated. You can however use the functionality if you update the the import paths

Instead of 

```python
from chemtools.gamessreader import GamessFortranReader, print_twoe, ijkl, factor
from chemtools.gamessus import GamessUS
```

use

```python
from chemtools.calculators.gamessreader import GamessFortranReader, print_twoe, ijkl, factor
from chemtools.calculators.gamessus import GamessUS
```

**Comment by hyh2022** [comment]
Dear Dr. Mental:
     Thanks! However, I have already used the true paths and solved this problem. The real problem that I wonder to know is something wrong in the module gamessreader.py.
In the line 109 of this module, the name 'twoe' is not defined. I have also described this in the issue.



Yours sincerely,
Hu Yihan


| |
huyihan_ahnu
|
|
***@***.***
|
On 2/1/2022 03:31，Lukasz ***@***.***> wrote：

The notebook you mention is not part of the official docs and is outdated. You can however use the functionality if you update the the import paths

Instead of

fromchemtools.gamessreaderimportGamessFortranReader, print_twoe, ijkl, factorfromchemtools.gamessusimportGamessUS

use

fromchemtools.calculators.gamessreaderimportGamessFortranReader, print_twoe, ijkl, factorfromchemtools.calculators.gamessusimportGamessUS

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hyh2022** [comment]
[https://github.com/lmmentel/chemtools/blob/master/chemtools/calculators/gamessreader.py](url)
` twoe.integrals.readinao(ints, filename)
[error.out.txt](https://github.com/lmmentel/chemtools/files/8004740/error.out.txt)
`

**Comment by lmmentel** [comment]
It's been some time since I used this but I think you would need a compile a fortran extension and uncomment https://github.com/lmmentel/chemtools/blob/02345f2a325757469c881c647e6c98b60338e151/chemtools/calculators/gamessreader.py#L43. The fortran code is here https://github.com/lmmentel/gamess-us-fortran-interface but unfortunately the documentation got lost.

Alternatively you could use the `SequentialFile` class https://github.com/lmmentel/chemtools/blob/02345f2a325757469c881c647e6c98b60338e151/chemtools/calculators/gamessreader.py#L313 to read the files you need directly but it requires some manual configuration. This feature was not fully release so there is limited documentation, but all the ingredients are there to make it work.

Sorry I cannot be more helpful but I haven't used the package for some time.

**Comment by hyh2022** [comment]
I am very grateful to you for helping me so far. So, you mean that if I compile the fortran code in https://github.com/lmmentel/gamess-us-fortran-interface, it will get the class called gamessusfortranext?


| |
huyihan_ahnu
|
|
***@***.***
|
On 2/6/2022 07:21，Lukasz ***@***.***> wrote：

It's been some time since I used this but I think you would need a compile a fortran extension and uncomment https://github.com/lmmentel/chemtools/blob/02345f2a325757469c881c647e6c98b60338e151/chemtools/calculators/gamessreader.py#L43. The fortran code is here https://github.com/lmmentel/gamess-us-fortran-interface but unfortunately the documentation got lost.

Alternatively you could use the SequentialFile class https://github.com/lmmentel/chemtools/blob/02345f2a325757469c881c647e6c98b60338e151/chemtools/calculators/gamessreader.py#L313 to read the files you need directly but it requires some manual configuration. This feature was not fully release so there is limited documentation, but all the ingredients are there to make it work.

Sorry I cannot be more helpful but I haven't used the package for some time.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
